services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend/src:/frontend/src
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/backend/src
  database:
    build: ./database
    ports:
      - "5555:3060"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: refMan
    